import os
from datetime import datetime
from fpdf import FPDF

class StudyTrackerPDF(FPDF):
    def header(self):
        self.set_fill_color(10, 10, 18)
        self.rect(0, 0, 210, 25, "F")
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(245, 200, 66)
        self.set_xy(0, 8)
        self.cell(0, 10, "ElGgolearn Academic Roadmap", align="C")

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by AI", align="C")

def create_study_tracker(roadmap, pdf_links, output_path):
    try:
        pdf = StudyTrackerPDF()
        pdf.set_auto_page_break(True, margin=20)
        pdf.add_page()
        pdf.set_fill_color(15, 15, 25)
        pdf.rect(0, 25, 210, 297, "F")

        # Cover
        pdf.set_y(50)
        pdf.set_font("Helvetica", "B", 30)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 15, roadmap.get("topic", "Course").upper(), align="C", ln=True)
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(245, 200, 66)
        pdf.cell(0, 10, f"Level: {roadmap.get('level', 'N/A')}", align="C", ln=True)

        for lv in roadmap.get("levels", []):
            pdf.add_page()
            pdf.set_fill_color(15, 15, 25)
            pdf.rect(0, 0, 210, 297, "F")
            
            pdf.set_y(35)
            pdf.set_font("Helvetica", "B", 18)
            pdf.set_text_color(245, 200, 66)
            pdf.cell(0, 10, f"Module {lv['id']}: {lv['title']}", ln=True)
            
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(200, 200, 200)
            pdf.multi_cell(0, 7, lv.get("summary", ""))
            
            pdf.ln(10)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(0, 255, 179)
            pdf.cell(0, 10, "Learning Checklist:", ln=True)
            
            pdf.set_text_color(255, 255, 255)
            for task in ["Watch Lectures", "Read PDF Materials", "Practice Exercises", "Final Quiz"]:
                pdf.cell(10, 8, "[ ]", ln=False)
                pdf.cell(0, 8, task, ln=True)

        pdf.output(output_path)
        return True
    except Exception as e:
        print(f"PDF Error: {e}")
        return False